{% set name = "cosmosis-build-standard-library" %}
{% set version = "1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 4be70b07dd6d557021327f30b8f8561c8e78a37c5e5201ab23968166dd408414

build:
  number: 2
  skip: true  # [( (py < 310) or win ) or ( (mpi == "openmpi") and linux )]
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - cosmosis
    # For compiling standard librarymodules
    - compilers
    - {{ mpi }}
    - llvm-openmp  # [osx]
    - libgomp  # [linux]
    - bzip2
    - cfitsio
    - gsl
    - fftw
    - libblas
    - liblapack
    - camb >=1.3.0
    - make
    - numpy
    # for running python standard library modules
    - astropy-base
    - cython
    - scikit-learn
    - fast-pt
    - deepdish
    - sacc

test:
  requires:
    - pytest
  commands:
    # Test local build
    - cosmosis-build-standard-library && cd cosmosis-standard-library && source cosmosis-configure && pytest -vv -s tests
    # Test in-place build
    - cosmosis-build-standard-library -i && cd  `python -c 'import cosmosis;print(cosmosis.__file__)' | xargs dirname` && cd cosmosis-standard-library && cosmosis demos/demo1.ini && cosmosis-postprocess demos/demo1.ini && test -f matter_power.png

about:
  home: https://github.com/joezuntz/cosmosis-standard-library
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: CosmoSIS Standard Library
  description: |
    This is a meta-package providing the dependencies for the CosmoSIS Standard
    Library.
  doc_url: https://cosmosis.readthedocs.io/
  dev_url: https://github.com/joezuntz/cosmosis

extra:
  recipe-maintainers:
    - joezuntz
    - marcpaterno
