{% set name = "cosmosis-build-standard-library" %}
{% set version = "1.2" %}
{% set version_for_conda = "1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version_for_conda }}

source:
  url:  https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e7f68f31d77b84563b7fce8b7256d142b232185758982b96e25ffb63e01a3e42

build:
  number: 11
  skip: True  # [(py < 36) or win]
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - cosmosis
    # For compiling standard librarymodules
    - compilers
    - {{ mpi }}
    - llvm-openmp  # [osx]
    - libgomp  # [linux]
    - bzip2
    - cfitsio
    - gsl
    - fftw
    - libblas
    - liblapack
    - camb >=1.3.0
    - make
    - numpy
    # for running python standard library modules
    - astropy-base
    - cython
    - scikit-learn
    - fast-pt
    - deepdish
    - sacc

test:
  requires:
    - pytest
  commands:
    # Test local build
    - cosmosis-build-standard-library && cd cosmosis-standard-library && source cosmosis-configure && pytest -v tests
    # Test in-place build
    - cosmosis-build-standard-library -i && cd  `python -c 'import cosmosis;print(cosmosis.__file__)' | xargs dirname` && cd cosmosis-standard-library && cosmosis demos/demo1.ini && cosmosis-postprocess demos/demo1.ini && test -f matter_power.png

about:
  home: https://github.com/joezuntz/cosmosis-standard-library
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: CosmoSIS Standard Library
  description: |
    This is a meta-package providing the dependencies for the CosmoSIS Standard
    Library.
  doc_url: https://cosmosis.readthedocs.io/
  dev_url: https://github.com/joezuntz/cosmosis

extra:
  recipe-maintainers:
    - joezuntz
    - marcpaterno
